### ISSUE TITLE
Lemon pb on BG/Q

### ISSUE THREAD

**Issue by MarianeBrinet** [etmc/tmLQCD#230]
I have a problem with Lemon on BG/Q; the error message I get when 
running inverter with Lemon is:

[LEMON] Node 5771 reports in lemonWriteLatticeParallel:
        Could not write the required amount of data.
[LEMON] Node 1568 reports in lemonWriteLatticeParallel:
        Could not write the required amount of data.

The "Lemon configure version" is 0.99 (written in the config.log file, but does it give the
Lemon version...?). I configured using

./configure --prefix=/workgpfs/rech/xgm/rxgm005/binaires/lemon CC=mpixlcxx CFLAGS=-I/bgsys/drivers/cfloor/comm/xl.ndebug/include -qstrict -O3

(removing -qstrict and/or -O3 does not solve the problem).

The error appears at run time, not when compiling. 

Please let me know if you need more information, and thanks in advance for your
help!

Mariane

**Comment by kostrzewa** [comment]
I guess we can close this.
