### ISSUE TITLE
Plaquette reporting broken when setting OMPNumThreads > 1

### ISSUE THREAD

**Issue by deuzeman** [etmc/tmLQCD#247]
This is for a run on a cluster, not sure what is going on. When I run a quenched simulation with just a single thread, the XLF-info record gives a reasonable

`plaquette = 0.521037726555`

Now when `OMPNumThreads` is set to 8, the code runs much faster as expected. But now the plaquette value is reported as

`plaquette = 2367026777804866748331923863210541984309341151776027807045523303964868700020050973202674476230208826886920232040761750964281237826029954421872289120650452372218491331992674268084258020790166767496709752057956054897665798832128.000000000000`

This is clearly less reasonable. This exact same value is spit out as run info, so it seems it's not just a printf statement going haywire. For what it's worth, the code does seem to run normally otherwise.

**Comment by urbach** [comment]
this has never been reproduced, as far as I can see, can we close this?

**Comment by kostrzewa** [comment]
Yeah, I'd like to close this.
