### ISSUE TITLE
Yet (slightly) wrong residue of clover inversion on bg/q 

### ISSUE THREAD

**Issue by florian-burger** [etmc/tmLQCD#269]
There seems to be a remaining issue with clover on bg/q as target residue (1.0e-16) is reached in the solver (see output below). However, on recalculating the residue it is of the order 1.0e-14!

Here is the output:
CG: iterations: 24826 res^2 3.113108e-17
sloppy precision on
CG: iterations: 24827 res^2 3.110795e-17
sloppy precision on
CG: iterations: 24828 res^2 3.102546e-17
sloppy precision on
CG: iterations: 24829 res^2 3.089907e-17
sloppy precision on
CG: iterations: 24830 res^2 3.076958e-17
# CG: iter: 24830 eps_sq: 1.0000e-16 t/s: 1.6427e+02
# CG: flopcount (for e/o tmWilson only): t/s: 1.6427e+02 mflops_local: 10343.6 mflops: 5295898.6
# Constructing LEMON writer for file source.0200.00.00.inverted for append = 1
# Time spent writing 1.02 Gb was 568 ms.
# Writing speed: 1.79 Gb/s (3.51 Mb/s per MPI process).
# Inversion done in 24830 iterations, squared residue = 1.562583e-14!
# Inversion done in 3.31e+02 sec. 

Here is the version that was used and its output:
Version 5.2.0, commit 7cf3784d3290fccac3018c2a125c7823af344607
# The code is compiled with QPX intrinsics for Blue Gene/Q
# Compiled with BG/Q SPI communication
# The code is compiled with -D_GAUGE_COPY
# The code is compiled with -D_USE_HALFSPINOR
# the code is compiled for non-blocking MPI calls (spinor and gauge)
# the code is compiled with MPI IO / Lemon
# the code is compiled with openMP support
# Periodic boundary conditions are used
# The lattice size is 96 x 48 x 48 x 48
# The local lattice size is 12 x 12 x 12 x 12
# Even/odd preconditioning is used
# beta = 6.000000 , kappa= 0.137290
# boundary conditions for fermion fields (t,x,y,z) \* pi: 1.000000 0.000000 0.000000 0.000000 
# beta = 6.000000, mu = 0.000900, kappa = 0.137290
# SPI using dynamic routing  zoneRoutingMask=0 stayOnBubbleMask=0
# SPI exchange successfully tested
#32 Bit SPI exchange successfully tested

This does not occur on Juropa, at least with version 
Version 5.2.0, commit 8d5fb0104b9a68f900eeb882a150c08c11bd47bb
that is used there:

CG: iterations: 26032 res^2 3.200980e-17
sloppy precision on
CG: iterations: 26033 res^2 3.188919e-17
sloppy precision on
CG: iterations: 26034 res^2 3.176778e-17
sloppy precision on
CG: iterations: 26035 res^2 3.163782e-17
# CG: iter: 26035 eps_sq: 1.0000e-16 t/s: 2.4432e+02
# CG: flopcount (for e/o tmWilson only): t/s: 2.4432e+02 mflops_local: 911.5 mflops: 
3733642.4
# Constructing LEMON writer for file source.0500.00.05.inverted for append = 1
# Time spent writing 1.02 Gb was 3.00 s.
# Writing speed: 340 Mb/s (82.9 kb/s per MPI process).
# Inversion done in 26035 iterations, squared residue = 3.365402e-17!
# Inversion done in 5.41e+02 sec.

**Comment by kostrzewa** [comment]
This has been resolved a while ago.
