### ISSUE TITLE
Trailing whitespace in input file makes it unreadable

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#276]
This is a bit of a silly usability problem. When a line in the input file has trailing whitespace, it causes the next line to fail to read:

```
BeginOperator TMWILSON{SPACE}
  kappa = 0.12
EndOperator
```

leads to

```
15:52 kostrzew@pax81 /lustre/fs4/group/etmc/kostrzew/eigcg_test $ ./invert        
Parsing error in line 29
Aborting...!
Could not make sense out off:  kappa=0.12
[1]    23759 exit 1     ./invert
````

**Comment by urbach** [comment]
hmm, I cannot reproduce this problem, I can add spaces after 'TMWILSON'...

**Comment by kostrzewa** [comment]
I might have fixed it at some point, I have a weak recollection of doing so at some point in time...

**Comment by kostrzewa** [comment]
Let's just close this then.
