### ISSUE TITLE
Hosting of related code

### ISSUE THREAD

**Issue by deuzeman** [etmc/tmLQCD#30]
There is some code related to tmLQCD, the repositories of which are currently hosted elsewhere. The obvious example is Lemon, which is even an optional dependency of tmLQCD. I'd say it makes sense to move (or at least mirror) these repositories here as well. It makes for a convenient one-stop process for those who just want to use the code. As for development, there are equally good reasons for moving away from SVN in these cases as there were for tmLQCD itself. 

The only significant downside I can think of would be that the current addresses may be provided in publications and presentations. We could fairly easily take care of this by providing tarballs there and/or merging patches back into public SVN repositories. In the case of Lemon, we should actually still be able to update the address.

Are there any objections that I am missing?

**Comment by martin-ueding** [comment]
The ETMC organziation on Github hosts a repository for Lemon. So this issue is closed?

**Comment by urbach** [comment]
yes, I think we can close this
