### ISSUE TITLE
about Dsw_psi() defined in operator/D_psi.h

### ISSUE THREAD

**Issue by sbacchio** [etmc/tmLQCD#333]
_Dsw_psi()_ defined in _operator/D_psi.h_ is just coded for the SSE version in _operator/D_psi.c_.

**Comment by kostrzewa** [comment]
No, that's not true:

```
#if (!defined SSE && !defined SSE2 && !defined SSE3)

#define _C_TYPE _Complex double
#define _F_TYPE double
#define _PSWITCH(s) s
#define _PTSWITCH(s) s

#include"D_psi_body.c"   <- non-SSE version defined here for float and double precision

#undef _C_TYPE
#undef _F_TYPE
#undef _PSWITCH
#undef _PTSWITCH

#else  <- SSE version comes after this
```

**Comment by kostrzewa** [comment]
Oh wait, no you're right.

**Comment by kostrzewa** [comment]
@urbach: what does this mean for our form factor computation on Jureca?

**Comment by kostrzewa** [comment]
Oh wait, no you're wrong, phew... If you look into "D_psi_body.c", D_psi there adds the clover term for g_c_sw > 0

**Comment by kostrzewa** [comment]
The way it is implemented, Dsw_psi() should never be used. Instead, D_psi should be called. When compiled with SSE, either the SW version or the TM version are used depending on the value of g_c_sw. In the case without SSE, D_psi() itself is specialised.

**Comment by urbach** [comment]
indeed, this was introduced by Abdou, and I didn't like it. He
introduced two operators by doubling a lot of code. But for
clover I didn't see another way for SSE. This should be removed/fixed
at some point.

> The way it is implemented, Dsw_psi() should never be used. Instead, D_psi should be called. When compiled with SSE, either the SW version or the TM version are used depending on the value of g_c_sw. In the case without SSE, D_psi() itself is specialised.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/tmLQCD/issues/333#issuecomment-230466434
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by sbacchio** [comment]
Ok, so I can use D_psi even with clover term. Because looking to M_psi and Q_psi, you have a different version for each of them (Mtm, Msw, Qtm, Qsw), so I tough that Dsw was the right one to be used. Maybe it's better to remove Dsw and Dtm from the header.

**Comment by kostrzewa** [comment]
I agree with your conclusion regarding the removal of Dsw_psi and Dtm_psi from the header. D_psi should be used (and is in fact used everywhere).

**Comment by sbacchio** [comment]
yes, that was the conclusion of this problem long time ago, for that reason I commented it (but I didn't remember). So shall I go ahead with that and remove them from the header? or keep the solution with the `#ifdef`?
it's the same from my point of view
