### ISSUE TITLE
DDalphaAMG interface MGSetup2KappaMu always zero

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#344]
@sbacchio In the DDalphaAMG interface, setting ```MGSetup2KappaMu``` always results in zero. I've checked the input file reader. I think the ```scanf``` statement requires numbers as well as letters (to capture the 2). Do you want to fix this in your branches and submit a pull-request at some point?

**Comment by sbacchio** [comment]
:+1:  ok should be fine now
