### ISSUE TITLE
DDalphaAMG breaks read_input.l

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#346]
@sbacchio @Finkenrath @urbach 
We overlooked a little something when we merged the DDalphaAMG branch. The lines in ```read_input.l``` which set MG parameters should be enclosed in ```#ifdef```, such that the code can be linked when the ```DDalphaAMG``` interface is not compiled. Alternatively, the MG parameters can be provided globally, also when ```DDalphaAMG``` is disabled.

**Comment by urbach** [comment]
can you provide a pull request for the required change?

> @sbacchio @Finkenrath @urbach 
> We overlooked a little something when we merged the DDalphaAMG branch. The lines in ```read_input.l``` which set MG parameters should be enclosed in ```#ifdef```, such that the code can be linked when the ```DDalphaAMG``` interface is not compiled. Alternatively, the MG parameters can be provided globally, also when ```DDalphaAMG``` is disabled.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/tmLQCD/issues/346
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by sbacchio** [comment]
Ah I've been too sloppy.
Sorry, I did a mess. I will fix it.

**Comment by kostrzewa** [comment]
This has been resolved by #347, closing.
