### ISSUE TITLE
Lime header xlf-information

### ISSUE THREAD

**Issue by sbacchio** [etmc/tmLQCD#351]
@urbach @kostrzewa 

We have noticed that the precision used for saving the information within the lime header is not enough. 
Indeed the new ensemble 64c128 with Nf=2 needs 7 digits for saving kappa but just 6 are used.

The files writing xlf in tmLQCD should be changed and they are: 
> io/eospinor_write.c
> io/params_construct_InverterInfo.c
> io/params_construct_xlfInfo.c
> io/utils_write_first_message.c
> io/utils_write_inverter_info.c
> io/utils_write_xlf.c
> io/utils_write_xlf_xml.c

Now the questions are: what precision should we use? "%.10f"? shall we change also other parameters?

Moreover we have the problem that the new configurations saved on Jureca have the wrong kappa in the header "0.137294 instead of 0.1372938". People should be aware of it.

**Comment by kostrzewa** [comment]
Indeed, I noticed this before but simply chose to ignore it for lack of time reasons.. I agree that it should be changed and noted in the Wiki for the tmclover runs.

**Comment by kostrzewa** [comment]
I think %.10f  is appropriate, but we can also do %.15f.

**Comment by kostrzewa** [comment]
Kappa is also printed in a number of places and only 6 digits are used.

**Comment by sbacchio** [comment]
Ok, when printed for the log is less important but I can fix it where it's easy to find.
For sure I will change it in the files listed before.
Shall I also change mu, 2KappaMu or other parameters as well?

**Comment by kostrzewa** [comment]
Sure, since you have to touch the files anyway, the effort will certainly not be wasted.
