### ISSUE TITLE
Building on Fedora 25

### ISSUE THREAD

**Issue by martin-ueding** [etmc/tmLQCD#360]
I'm trying to build tmLQCD on Fedora 25. I get an error around BLAS:

```
/usr/bin/gcc -o hmc_tm -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/home/mu/lib -L./lib -L./lime/lib/  hmc_tm.o   -lhmc -lmonomial -loperator -lsolver -linit -lmeas -llinalg -lhmc -lxchange -lrational -lio -llapack -llime   -L/usr/lib/gcc/x86_64-redhat-linux/6.3.1 -L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../.. -lgfortran -lm -lquadmath -lm
/usr/bin/ld: ./lib/libsolver.a(incr_eigcg.o): undefined reference to symbol 'zcopy_'
/usr/lib64/libblas.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:120: recipe for target 'hmc_tm' failed
```
Those are the packages that I have intalled for building:

```bash
BuildRequires:  libstdc++-devel autoconf gcc-c++ automake flex lapack-devel
Requires:       libstdc++ lapack
```

And those are the commands that I have used to compile it from a clean download from the most recent `master` from this repository. The `git_hash.h` is missing, but I just create it myself:

```bash
%global cxxflags "-O2 --std=c++11 -fopenmp -g -fPIC"
%global cflags "-O2 --std=c99 -fopenmp -g -fPIC"

echo "#ifndef _GIT_HASH_H" > git_hash.h
echo "#define _GIT_HASH_H" >> git_hash.h
echo "const char git_hash[] = {\"%{commit0}\"};" >> git_hash.h
echo "#endif /* _GIT_HASH_H */" >> git_hash.h

autoconf

%configure \
        --disable-mpi \
        CC=/usr/bin/gcc \
        CXX=/usr/bin/g++ \
        CFLAGS=%{cflags} \
        CXXFLAGS=%{cxxflags} || (cp config.log /tmp/ && exit 1)

make 
```

From what I read, there seems to be some flag missing for blas, like `-lz` or something else. What do I need to change to get it to build?

**Comment by urbach** [comment]
You do not link against blas, do you? So, I guess it cannot link. 

How did you manage to configure this? Are you using the configure coming with TMLQCD? 

Am 10. April 2017 21:23:38 MESZ schrieb Martin Ueding <notifications@github.com>:
>I'm trying to build tmLQCD on Fedora 25. I get an error around BLAS:
>
>```
>/usr/bin/gcc -o hmc_tm -Wl,-z,relro
>-specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/home/mu/lib -L./lib
>-L./lime/lib/  hmc_tm.o   -lhmc -lmonomial -loperator -lsolver -linit
>-lmeas -llinalg -lhmc -lxchange -lrational -lio -llapack -llime  
>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1
>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../lib64
>-L/lib/../lib64 -L/usr/lib/../lib64
>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../.. -lgfortran -lm
>-lquadmath -lm
>/usr/bin/ld: ./lib/libsolver.a(incr_eigcg.o): undefined reference to
>symbol 'zcopy_'
>/usr/lib64/libblas.so.3: error adding symbols: DSO missing from command
>line
>collect2: error: ld returned 1 exit status
>Makefile:120: recipe for target 'hmc_tm' failed
>```
>Those are the packages that I have intalled for building:
>
>```bash
>BuildRequires:  libstdc++-devel autoconf gcc-c++ automake flex
>lapack-devel
>Requires:       libstdc++ lapack
>```
>
>And those are the commands that I have used to compile it from a clean
>download from the most recent `master` from this repository. The
>`git_hash.h` is missing, but I just create it myself:
>
>```bash
>%global cxxflags "-O2 --std=c++11 -fopenmp -g -fPIC"
>%global cflags "-O2 --std=c99 -fopenmp -g -fPIC"
>
>echo "#ifndef _GIT_HASH_H" > git_hash.h
>echo "#define _GIT_HASH_H" >> git_hash.h
>echo "const char git_hash[] = {\"%{commit0}\"};" >> git_hash.h
>echo "#endif /* _GIT_HASH_H */" >> git_hash.h
>
>autoconf
>
>%configure \
>        --disable-mpi \
>        CC=/usr/bin/gcc \
>        CXX=/usr/bin/g++ \
>        CFLAGS=%{cflags} \
>        CXXFLAGS=%{cxxflags} || (cp config.log /tmp/ && exit 1)
>
>make 
>```
>
>From what I read, there seems to be some flag missing for blas, like
>`-lz` or something else. What do I need to change to get it to build?

-- 
Carsten Urbach, www.carsten-urbach.eu

**Comment by urbach** [comment]
There is a configure option

--with-lapack=

or so, sorry, I'm on my mobile right now. There you can specify the needed options. But I'd thought that configure does not complete, because it should check this. 

Am 10. April 2017 21:30:25 MESZ schrieb Carsten Urbach <urbach@hiskp.uni-bonn.de>:
>You do not link against blas, do you? So, I guess it cannot link. 
>
>How did you manage to configure this? Are you using the configure
>coming with TMLQCD? 
>
>Am 10. April 2017 21:23:38 MESZ schrieb Martin Ueding
><notifications@github.com>:
>>I'm trying to build tmLQCD on Fedora 25. I get an error around BLAS:
>>
>>```
>>/usr/bin/gcc -o hmc_tm -Wl,-z,relro
>>-specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/home/mu/lib -L./lib
>>-L./lime/lib/  hmc_tm.o   -lhmc -lmonomial -loperator -lsolver -linit
>>-lmeas -llinalg -lhmc -lxchange -lrational -lio -llapack -llime  
>>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1
>>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../../../lib64
>>-L/lib/../lib64 -L/usr/lib/../lib64
>>-L/usr/lib/gcc/x86_64-redhat-linux/6.3.1/../../.. -lgfortran -lm
>>-lquadmath -lm
>>/usr/bin/ld: ./lib/libsolver.a(incr_eigcg.o): undefined reference to
>>symbol 'zcopy_'
>>/usr/lib64/libblas.so.3: error adding symbols: DSO missing from
>command
>>line
>>collect2: error: ld returned 1 exit status
>>Makefile:120: recipe for target 'hmc_tm' failed
>>```
>>Those are the packages that I have intalled for building:
>>
>>```bash
>>BuildRequires:  libstdc++-devel autoconf gcc-c++ automake flex
>>lapack-devel
>>Requires:       libstdc++ lapack
>>```
>>
>>And those are the commands that I have used to compile it from a clean
>>download from the most recent `master` from this repository. The
>>`git_hash.h` is missing, but I just create it myself:
>>
>>```bash
>>%global cxxflags "-O2 --std=c++11 -fopenmp -g -fPIC"
>>%global cflags "-O2 --std=c99 -fopenmp -g -fPIC"
>>
>>echo "#ifndef _GIT_HASH_H" > git_hash.h
>>echo "#define _GIT_HASH_H" >> git_hash.h
>>echo "const char git_hash[] = {\"%{commit0}\"};" >> git_hash.h
>>echo "#endif /* _GIT_HASH_H */" >> git_hash.h
>>
>>autoconf
>>
>>%configure \
>>        --disable-mpi \
>>        CC=/usr/bin/gcc \
>>        CXX=/usr/bin/g++ \
>>        CFLAGS=%{cflags} \
>>        CXXFLAGS=%{cxxflags} || (cp config.log /tmp/ && exit 1)
>>
>>make 
>>```
>>
>>From what I read, there seems to be some flag missing for blas, like
>>`-lz` or something else. What do I need to change to get it to build?

-- 
Carsten Urbach, www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
```git_hash``` should be generated automatically if git is available. Otherwise it is simply filled with the version string.

As for blas/lapack: ```--with-lapack="-llapack -lblas"``` will do it on most "simple" systems. You might need to set ```F77=gfortran``` as well

On more complicated systems, with the Intel compiler, say, something like this is required:

https://github.com/etmc/tmLQCD/wiki/Juropatest

**Comment by martin-ueding** [comment]
Thanks, I have added the two linker flags, as well as an OpenMP flag:

```bash
%configure \
        --disable-mpi \
        --with-lapack='-llapack -lblas' \
        CC=/usr/bin/gcc \
        CXX=/usr/bin/g++ \
        CFLAGS=%{cflags} \
        LIBS='-fopenmp' \
        || (cp config.log /tmp/ && exit 1)
```

Now it builds! :smile: 

There are now [RPM packages for Fedora 24 and 25](https://build.opensuse.org/package/show/home:martinueding/tmLQCD). Thanks for the hints!
