### ISSUE TITLE
DDalphaAMG with odd number of processes in some direction

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#392]
@sbacchio 
Is there an issue with using DDalphaAMG with an odd number of processes in some direction? I've tried the following:

```
48^3 x 96 lattice
3x6x6x12 (xyzt) processes for parallelisation (24nodes * 54 processes)
local lattice size: 16*8^3 (xyzt)
aggregration: 4^4 blocks at depth 0 -> 2 2 2 4 blocks (TZYX)
                        2^4 blocks at depth 1 -> 1 1 1 2 blocks (TZYX)
                        1^4 blocks at depth 2 -> 1 1 1 2 blocks for OE GMRES
```

Unfortunately, this crashes, at least on Marconi A2 (haven't tested elsewhere). Is this because the number of blocks in X direction is even but the number of processes is odd? The same aggregation works for a 

```
6x6x6x6 parallelisation
```

but ideally one would like to have 16 lattice sites in X direction because it benefits QPhiX performance significantly. If it's just not possible, then we'll just have to live with slightly lower performance on the 48c96 lattices.

**Comment by sbacchio** [comment]
I don't see problems in what you are trying.. it should work. How does it crash? Can you please attach a log and error file?

**Comment by sunpho84** [comment]
I have in the back of my mind that it was crashing for this kind of reason with some version (or branch), and not in other ones...

**Comment by kostrzewa** [comment]
@sbacchio sorry that it took me so long to get back to this. It turns out that this was not related to DDalphaAMG at all, it just happened that DDalphaAMG output was the last thing I saw before it went down.
