### ISSUE TITLE
merge of DDalphaAMG_nd and qphix_hmc_devel branches for merge into master

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#395]
@sbacchio, @Finkenrath, @urbach  : I would like to merge the production version of the ```DDalphaAMG_nd``` branch with my ```qphix_hmc_devel``` branch to then proceed to pull-request into etmc/master. Does this correspond to the actual production version? https://github.com/Finkenrath/tmLQCD/commits/DDalphaAMG_nd

**Comment by kostrzewa** [comment]
*ping*

**Comment by urbach** [comment]
this is -- in my opinion -- very important!

> *ping*
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/tmLQCD/issues/395#issuecomment-325108037
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by sbacchio** [comment]
Sorry but the DDalphaAMG_nd is not ready yet for being merged.
I've still some things to fix and improve.
I would prefer the opposite: that `qphix_hmc_devel` is merged to the master and then I will add my changes. I don't think the two part overlap, or? 
Otherwise I think it will be ready in the next week or so.

**Comment by kostrzewa** [comment]
Okay, fine. I've made quite a number of changes to various solver interfaces and would like to start production on Marconi ASAP. But I can begin with the ND doublet without DDalphaAMG and move to the DDalphaAMG-accelerated multi-shift later.

**Comment by kostrzewa** [comment]
I do believe there might be some overlap in the monomial_solve wrappers for the heavy doublet and monomial_solve in general.

**Comment by sbacchio** [comment]
No problem for solving the conflicts. 
I'm sorry for not pushing it now, but otherwise I would have to do additional pull requests after. 
We did some more improvements recently but they are not definitive yet.
The speed-up for the rational approximation should be higher than what is now.

**Comment by kostrzewa** [comment]
Okay, I think we can close this as we are making progress.
