### ISSUE TITLE
Time for merges

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#419]
@urbach @marcus-petschlies @martin-ueding @sbacchio @Finkenrath @sunpho84 @pittlerf

We need to agree to process the pull-requests in the next few weeks or so at the latest. A lot of important stuff has accumulated and code divergence is making it difficult to bring together new developments.

**Comment by urbach** [comment]
> @urbach @marcus-petschlies @martin-ueding @sbacchio @Finkenrath @sunpho84 @pittlerf
> 
> We need to agree to process the pull-requests in the next few weeks or so at the latest. A lot of important stuff has accumulated and code divergence is making it difficult to bring together new developments.

I agree. How should we oranise this?

Carsten

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/etmc/tmLQCD/issues/419
--
Carsten Urbach
e-mail: curbach@gmx.de
        urbach@hiskp.uni-bonn.de
Fon   : +49 (0)228 73 2379
skype : carsten.urbach
URL: http://www.carsten-urbach.eu

**Comment by kostrzewa** [comment]
@Finkenrath @sbacchio 
Just wanted to ask what the status on the DDalphaAMD_nd branch is and when we could expect merging to proceed.
