### ISSUE TITLE
error under kernel 3.10 on multiple nodes

### ISSUE THREAD

**Issue by MadNazgul** [etmc/tmLQCD#440]
Hello, tmLQCD Team!

We try to build last tmLQCD from your github under Scientific Linux 7.5 (kernel 3.10.0-862.6.3) with LIME 1.3.2 and Intel MPI by Intel Compiler 2018. The build process was successful. The run of the binary code on one worknode was correct. The run the same code on multiple worknodes (e.g. two worknodes) we got the errors like issue #430.

Also this source code was built under Scientific 6.10 (kernel 2.6.32-754.6.3) with LIME 1.3.2 and Intel MPI by Intel Compiler 2013. There is no difference between runs on one worknode or on multiple worknodes. There is no errors in this case.

Do you have any issue about unsuccessfully runs of binary code with LIME library under kernel 3.10?

**Comment by MadNazgul** [comment]
Yes, it is. We use NFS v4.1 and for test purpose we switched back to NFS v3. The error is exist anyway with kernel 3.10. In case of kernel 2.6.32 the filesystem is the same too and it is AFS (kmod-openafs 1.6.22.3).

**Comment by kostrzewa** [comment]
Did you try lemon instead? I'm a bit surprised that you're seeing issues since we've never seen problems and lime has been basically not changed for decades...

**Comment by kostrzewa** [comment]
Could you provide more details on the input file and how you launched the job?

**Comment by kostrzewa** [comment]
Finally, did you check that the file that you are trying to read actually contains the relevant headers? The tools in the lime package, such as ```lime_contents``` will allow you to check this.

**Comment by MadNazgul** [comment]
Well, by your advise we will try to link tmLQCD with LEMON library at first. About results we will write here.

**Comment by kostrzewa** [comment]
My advice would be to check the file first :)

**Comment by urbach** [comment]
well, actually, in order to be able to help here we need much more
details!

> My advice would be to check the file first :)

my understanding was that the serial run had no problems reading the file?

**Comment by MadNazgul** [comment]
Our investigations with tmLQCD and LEMON are written below:

1) The source code was built with LEMON and run on kernel 3.10 was successful on NFS.
2) The source code was built with LEMON and run on kernel 2.6.32 was unsuccesfull on AFS.
One node run was complete without error. Two nodes run was correct but has this message on output and without any working output files.

```
Your MPI job will continue, but may be behave poorly and/or hang.
--------------------------------------------------------------------------
  Direction for polyakov loop set to 0
[wni020.jinr.ru:26637] 7 more processes have sent help message help-mpi-btl-openib.txt / reg mem limit low
[wni020.jinr.ru:26637] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
mpiexec: killing job...
```
3) The source code was built with LEMON and run on kernel 2.6.32 was unsuccessful on LUSTRE.
One node run was correct but has this error on output:

```
This requires fcntl(2) to be implemented. As of 8/25/2011 it is not. Generic MPICH Message: File locking failed in ADIOI_Set_lock(fd 18,cmd F_SETLKW/7,type F_WRLCK/1,whence 0) with return value FFFFFFFF and errno 26.
- If the file system is NFS, you need to use NFS version 3, ensure that the lockd daemon is running on all the machines, and mount the directory with the 'noac' option (no attribute caching).
- If the file system is LUSTRE, ensure that the directory is mounted with the 'flock' option.
ADIOI_Set_lock:: Function not implemented
ADIOI_Set_lock:offset 0, length 8
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
rm: cannot remove `/tmp/genmachines.n87s4s': no such file or directory

```
Temporary file (.conf.t00000.tmp) has only header but hasn't any data record:

```
Eg###xlf-infoplaquette = 0.315874826327
 trajectory nr = 0
 beta = 2.100000000000, kappa = 0.156361000000, mu = 0.001500000000, c2_rec = -0.331000
 time = 1540578987
 hmcversion = 5.2.0
 mubar = 0.120000000000
 epsilonbar = 0.138500000000
 date = Fri Oct 26 21:36:27 2018

```
Two nodes run has the same error and issue with temporary file.

**Comment by kostrzewa** [comment]
It seems that the problems stem from the configuration of the NFS and Lustre file systems that you've tried this on. I'm afraid there's not much more that I can help with here, I guess...

In the run with LIME that you did before, during what operation exactly did the failure occur? During the re-read test? Was the temporary file written and complete in that case?

**Comment by MadNazgul** [comment]
One of previous run with LIME only on kernel 3.10 with computation on 2
nodes per 4 processes get this type of errors for every ``conf.XXX`` files
```
# Trajectory is accepted.
# Writing gauge field to .conf.t00000.tmp.
LIME record with name: "ildg-format", in gauge file .conf.t00000.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00000.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00000.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00000.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
# Write completed, verifying write...
# Write successfully verified.
# Renaming .conf.t00000.tmp to conf.save.
#
# Beginning online measurement.
#
# Starting trajectory no 1
# Trajectory is accepted.
# Writing gauge field to .conf.t00001.tmp.
LIME record with name: "ildg-format", in gauge file .conf.t00001.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00001.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00001.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
LIME record with name: "ildg-format", in gauge file .conf.t00001.tmp either
missing or malformed.
Unable to verify gauge field size or precision.
# Write completed, verifying write...
# Write successfully verified.
# Renaming .conf.t00001.tmp to conf.0000.
```
Writing of all ``conf.XXX`` files were completed and they have the same
size.

We continue solve problem with Lustre and AFS by ourselves.

Thank you for your advice with LEMON library!
Can I close this issue?
