### ISSUE TITLE
quda_work branch: MGSmootherType and MGCoarseSolverType should be case-insensitive

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#453]
@pittlerf in the ```quda_work``` branch, the setting of smoothers and solvers works quite nicely on a per-level basis, but the strings are currently case-sensitive. In ```read_input.l```, before you do strcmp, there should be a conversion to lower case of the input string for these settings.

**Comment by kostrzewa** [comment]
@pittlerf should I make this change myself?

**Comment by pittlerf** [comment]
Sorry, I did that, I just forgot the pull request

**Comment by kostrzewa** [comment]
thanks!
