### ISSUE TITLE
Wrapper: Reading the gauge fields, related to peram_gen

### ISSUE THREAD

**Issue by pittlerf** [etmc/tmLQCD#456]
In case the checksum matching fail in the reading routine ("read_gauge_field") the routine tmLQCD_read_gauge writes an error message to stderr and returning with the value -1. 
However, the main function in the peram_gen ignores this return value and the execution will continue.
My suggestion is to either modify peram_gen:

int reading_flag=  tmLQCD_read_gauge(param.config);
if (reading_flag == -1){
    fprintf(stderr,"Error occured in reading the gauge configuration\n");
    exit(1);
}

or do the modification in tmLQCD:
instead of return(-1) to exit(1)

What do you think?

**Comment by kostrzewa** [comment]
Thanks. I've made the necessary modification to ```peram_gen```.
