### ISSUE TITLE
restoresu3_flag stuff

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#464]
@Finkenrath I would like to remove all mention of ```restoresu3_flag``` from the code (in the DDalphaAMG_nd_merge_etmc_master branch which I'm readying for merging into master). It seems to me that this amounts to a whole bunch of testing code which doesn't do anything, especially now that your more complete su3 restoration is in the codebase. Do you agree?

**Comment by Finkenrath** [comment]
@kostrzewa yes, we agree. The flag was used for checking and can be removed (At this point one could also think about to save only two rows of the SU3-matrices. After projection the info of the third row is anyway gone.) .

**Comment by kostrzewa** [comment]
Okay, I'll proceed then. About the storage, this would mean that we would need to equip lime or lemon or every code that we use we su3 restoration facilities. It would also break compatibility with the lime format. Neither of these two reasons are dealbreakers, of course, but they do mean extra work...

**Comment by kostrzewa** [comment]
The space saving is of course tempting with the large lattices that we are working with now...

**Comment by kostrzewa** [comment]
Done.
