### ISSUE TITLE
quda_interface: expose pipelining

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#465]
To help with strong scaling, pipelining should be exposed as a setting for solvers. The details of how to do this in a fine-grained enough fashion to be useful are a bit complicated I think. See https://github.com/lattice/quda/issues/692 for some hints.

**Comment by kostrzewa** [comment]
@urbach @martin-ueding @pittlerf  @marcus-petschlies  anybody willing to work on this?

**Comment by urbach** [comment]
> @urbach @martin-ueding @pittlerf  @marcus-petschlies  anybody willing to work on this?

Important topic, however, given my recent failure: it does not seem
realistic for me timewise to work on this in a reasonable timeframe.
