### ISSUE TITLE
incorporate changes to QUDA eigensolver interface

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#476]
Via @cpviolator:

> Just wanted to let you know that we made a few minor changes to the Eigensolver interface. Nothing functional, just conventions. Your scripts and code will need to reflect the following case changes:
> nEv -> n_ev
> nKr -> n_kr
> nConv -> n_conv
>
> and a new addition,
>
> n_ev_deflate
>
> will allow you to compute N eigenvectors, but use only M <= N for deflation. Useful if you want to study wall clock speed up as a function of M by saving and reloading N vectors.

In tmLQCD, these should be ```#ifdef```'ed via ```TM_QUDA_EXPERIMENTAL``` to preserve compatibility with our current production QUDA version.

@marcuspetschlies This might affect you too if you upgrade your production QUDA version.

**Comment by marcuspetschlies** [comment]
Yes, I had already been changing that in my fork
