### ISSUE TITLE
parser cannot deal with minus signs in FILENAME

### ISSUE THREAD

**Issue by kostrzewa** [etmc/tmLQCD#478]
`GaugeConfigInputFile = this-is-a-dir/conf` does not work

**Comment by urbach** [comment]
that is strange, because it is included in `FILENAME`. From `read_input.l`:

    FILENAME [a-zA-Z0-9_".""-""/"][a-zA-z0-9"."_"-""/"]+

**Comment by urbach** [comment]
maybe it needs to be `\-`...?
