### ISSUE TITLE
Multiple definition of X1,X2,X3,X0 in quda_interface.c and boundary.c

### ISSUE THREAD

**Issue by sunpho84** [etmc/tmLQCD#484]
This time I have more trouble understanding the fix, indeed I get the following error

```
multiple definition of `X1'; ./lib/libhmc.a(boundary.o):/home/francesco/QCD/SORGENTI/tmLQCD/build_quda/../boundary.c:38: first defined here
[...more for X2 X3 X0]
```

I'm not sure to understand if the two set of variables are meant to be the same (in which case I would suggest removing them from `quda_interface.c`, and adding the appropriate `extern` in the` boundary.h` header) or if they are meant to stay different, in which case I would suggest renaming the quda version.

**Comment by kostrzewa** [comment]
Agreed, the quda interface seems to work correctly "by accident" what concerns the X[0,1,2,3]. Their redeclaration is certainly not correct here.

**Comment by sunpho84** [comment]
So if they don't have to be redeclared, I'll remove them and add the appropriate `extern` in `boundary.h`

**Comment by kostrzewa** [comment]
I think we first need to merge master into quda_work, do regression tests and then see from there. The branches have diverged too much at this stage.

**Comment by kostrzewa** [comment]
I'm performing the merge right now, the changes are mostly cosmetic so far. 70 files to go.
