### ISSUE TITLE
qbig: Blocking error

### ISSUE THREAD

**Issue by simone-romiti** [etmc/tmLQCD#574]
@kostrzewa 
Testing the ndd correlators omeas implementation.
I experience the following:

/hiskp4/romiti/tmLQCD_runs/ndd_correlators/jobscript/logs/test-nd_correlators.173765.*

**Comment by kostrzewa** [comment]
Your title, "Blocking error", suggests that you have a configuration for an MG setup in there. The MG setup of course needs to be such that the block sizes and the volume per MPI task fit together.

**Comment by kostrzewa** [comment]
If you're testing with a 24c48 lattice, for example, then a

```
MGBlockSizesX = 4,3
MGBlockSizesY = 4,3
MGBlockSizesZ = 2,3
MGBlockSizesT = 3,2
```

blocking might be an option which works (assuming you're on a single node and have partitioned in T and Z only in a 4x2 grid (4 in T, 2 in Z) such that you have 12 fine grid points in the T and Z directions per MPI task.

The number of lattice points in each dimension at each level needs to be even and the size of the 4D blocks needs to be even as well.
